##--Database Config--##
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=DU_AN_TOT_NGHIEP
    username: sa
    password: 12345
##--Spring Data Jpa Config--##
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
##--Mail config--##
  mail:
    host: smtp.gmail.com
    port: 587
    username: phatndph09427@fpt.edu.vn
    password: lwkx tqqi cxef qhci
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true